import "@/styles/globals.css";
import { useState, useEffect } from "react";
import { UserContext } from "../lib/UserContext";
import { useRouter } from "next/router";
import { magic } from "@/lib/magic";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  const [user, setUser] = useState();
  const router = useRouter();

  useEffect(() => {
    magic.user.isLoggedIn().then((isLoggedIn) => {
      if (isLoggedIn) {
        magic.user.getMetadata().then((userData) => {
          setUser(userData);
        });
      } else {
        setUser({ user: null });
      }
    });
  }, []);

  return (
    <UserContext.Provider value={[user, setUser]}>
      <Head>
        <title>Magic Auth Practice App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </UserContext.Provider>
  );
}
